#include "WidgetDrawablesDetailCommon.inl"
#include "WidgetDrawablesDetailButton.inl"
#include "WidgetDrawablesDetailToggle.inl"
#include "WidgetDrawablesDetailSlider.inl"
#include "WidgetDrawablesDetailList.inl"
#include "WidgetDrawablesDetailStack.inl"
